[package]
name = "dynamic-layout"
version = "0.1.0"
edition = "2021"
license = "mit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynisland-core = { path = "../../core" }
dynisland-abi = { path = "../../abi" }

anyhow = { workspace = true }
gtk = { workspace = true, features = ["unsafe-assume-initialized"] }
gtk-layer-shell = { workspace = true }
gdk = { workspace = true }
glib = { workspace = true }
# glib-macros = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "sync", "macros"] }
serde = { workspace = true, features = ["serde_derive"] }
ron = { workspace = true }
abi_stable = { workspace = true }
# grass = { workspace = true }

log = { workspace = true }
env_logger = { workspace = true }

[lib]
name = "dynamic_layoutmanager"
crate-type = ["cdylib", 'rlib']
